import type { ThemeConfig } from '../ThemeProvider'

const minimal: ThemeConfig = {
  name: 'minimal',
  displayName: 'Light Minimal',
  colors: {
    pageBg: '#eeecea',
    pageBgElevated: '#ffffff',
    pageText: '#1a1917',
    textMuted: '#6b6a67',
    textDim: '#b0aead',
    titlebarBg: '#ffffff',
    titlebarBorder: '#e0dedd',
    titlebarGlow: 'rgba(26,25,23,0.06)',
    sidebarBg: '#f8f7f5',
    sidebarElevatedBg: '#ffffff',
    sidebarBorder: '#e0dedd',
    panelBg: '#ffffff',
    panelElevatedBg: '#f8f7f5',
    panelBorder: '#e0dedd',
    terminalBg: '#ffffff',
    terminalToolbarBg: '#ffffff',
    terminalInputBg: '#ffffff',
    aiPanelBg: '#ffffff',
    aiPanelBorder: '#e0dedd',
    cardBg: '#f8f7f5',
    cardBorder: '#e0dedd',
    cardActiveBg: '#f2f0ed',
    cardActiveBorder: '#1a1917',
    inputBg: '#ffffff',
    inputBorder: '#d0cecc',
    inputPlaceholder: '#b0aead',
    inputFocus: '#1a1917',
    accent: '#1a1917',
    accentSoft: '#f2f0ed',
    accent2: '#2563eb',
    accent3: '#16a34a',
    green: '#16a34a',
    yellow: '#d97706',
    red: '#dc2626',
    cursorColor: '#1a1917',
    promptColor: '#6b6a67',
    badgeBg: '#f2f0ed',
    badgeBorder: '#d0cecc',
    badgeText: '#6b6a67',
    statusOnline: '#16a34a',
    statusWarn: '#d97706',
    statusOffline: '#b0aead',
    shadow: '0 20px 56px rgba(16,24,40,0.08), 0 1px 2px rgba(16,24,40,0.08)',
    overlay: 'rgba(26,25,23,0.035)',
  },
  fonts: {
    shell: "'IBM Plex Mono', monospace",
    ui: "'DM Sans', sans-serif",
  },
  animations: {
    scanline: false,
    grid: false,
    glow: false,
  },
}

export default minimal
